name: media_repository
description: Maneja el recurso de las fotos, videos y audios que pueden tener el app.
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  equatable: 2.0.3
  http: 0.13.3
  user_repository:
    path: ../user_repository