name: media_repository
description: Paquete de Dart que maneja el endpoint de filtering/media
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  http: ^0.13.3